### PR TITLE
Changed docker_build workflow to push to ghcr

### PR DESCRIPTION
**Pull request by TonyRowntree**
**Changelog**
- Updated the docker_build.yml Bevel and Corda jobs to now push to ghcr.io instead of DockerHub.

**Reviewed by**

 

**Linked issue**
#1780

### CODE REVIEW

**Comment by TonyRowntree** [comment]
@suvajit-sarkar @sownak this is now ready for review

**Comment by TonyRowntree** [comment]
image

**Comment by jagpreetsinghsasan** [comment]
Why do we have a separate file for docker build ghcr?
There should be only file .github/workflows/docker_build.yml which shall now be pushing to ghcr instead of dockerhub registry.
Right @suvajit-sarkar ?

**Comment by TonyRowntree** [comment]
> 
Updated to have only a single file 👍🏼

**Review by suvajit-sarkar — APPROVED** [review]

**Review by suvajit-sarkar — APPROVED** [review]

**Pull request merged**
