### PR TITLE
[fabric] Multiple operations fix after ansible decoupling changes

### PR DESCRIPTION
**Pull request by prasanths96**
**Changelog**
- **Add peer to org:** https://github.com/hyperledger/bevel/pull/1940/commits/aef4ecde31a4d52c80f5e15b7e16b9965541c18e https://github.com/hyperledger/bevel/commit/d928beedde25ebf74bda46776453f643af2b240f
    - `platforms/hyperledger-fabric/configuration/add-peer.yaml`: "create/crypto/peer" role was no more available & replaced
    - `platforms/hyperledger-fabric/charts/catools/templates/configmap.yaml`: store-vault-peer.sh logic fix: If peer status is not "new" or "", then move on to next peer.
    - `platforms/hyperledger-fabric/configuration/roles/create/ca-tools/peer/tasks/main.yaml`:  The export syntax: 
    `export VARIABLE=$VALUE` does not seem to work in the sh used in bevel. Instead two line approach works `VARIABLE=$VALUE; export VARIABLE`. Ref: [Link](https://stackoverflow.com/questions/7328223/unix-export-command)
    
- **Add raft orderer to org:** https://github.com/hyperledger/bevel/pull/1940/commits/97394ca400b89330dba2b8f8de95eb883aee5a51
    - `platforms/hyperledger-fabric/configuration/add-orderer.yaml`: "create/crypto/orderer" role was no more available & replaced
    - `platforms/hyperledger-fabric/configuration/roles/create/ca-tools/orderer/tasks/main.yaml`: Export syntax change
    
- **Removing org:** https://github.com/hyperledger/bevel/pull/1940/commits/e7951c5dd49445cd87d49a2d45e5be0cc1b4d1ac
    - `platforms/hyperledger-fabric/configuration/roles/setup/config_block/sign_and_update/tasks/main.yaml`: Changed condition to also involve the org being deleted to sign the config update block. 
    In a 3 org setup `{supplychain (orderer), carrier, manufacturer}`, removing one of the peer orgs lead to error indicating channel update policy not being met. Making the above change fixes this.

### CODE REVIEW

**Comment by jagpreetsinghsasan** [comment]
Hi @prasanths96 
Thanks for the showing interest in Bevel and the code contribution. Give us sometime for this to be re-checked once from our end as well (as you are aware that these roles are used in many operational features and it will take some time for checking), and then we will get back to you with good-to-merge/requested-changes.

**Comment by prasanths96** [comment]
@jagpreetsinghsasan Alright, thanks!

**Comment by sownak** [comment]
@prasanths96 thanks for this PR, our PR #1956 contains your changes and more. You may want to take the latest from develop and test your cases.

**Comment by pras-spydra** [comment]
Hmm.. So if it works in the current develop branch, this PR will be closed? This pr 17 days old, It puts me off to see same changes getting merged from another pull request that was created 2 days ago as if this pr wasn't taken seriously.

**Comment by sownak** [comment]
@prasanths96 This PR has been taken seriously, and hence our team took time to test that all functionalities were working with the changes you have made. In that process, they found other issues and fixed them too. I am sure your PR still contains important fixes. You can merge and update this PR.

**Comment by pras-spydra** [comment]
@sownak Thank you!

**Comment by jagpreetsinghsasan** [comment]
The PR indeed was taken seriously by the team and we took this on the highest priority. As the changes spanned over a large piece of fabric deployment code, we had to perform thorough testing against all the fabric operational features, fixing other issues during the testing phase (#1956)
We highly appreciate community participation.

**Pull request merged**
