### PR TITLE
Added application molecule test in CI

### LINKED ISSUE #738: Add Application molecule tests in GitActions
### Description
As a developer I want to run all Example application Molecule test Scenarios so that the Git Actions flow is complete for Applications.
Add a condition so that the Application tests are run only when the check-in has a "[application]" in the commit message

### Acceptance Criteria
1. GitActions test should run for Sample applications when commit message has "[application]"
2. All Application molecule test scenarios should be run for both supplychain and identity. (this can be separated if the tests take more than 5 minutes to run)
3. Tests should run parallelly for supplychain and identity app

### PR DESCRIPTION
**Pull request by octonawish-akcodes**
fixes #738 

Need reviews @sownak @suvajit-sarkar @jagpreetsinghsasan

### CODE REVIEW

**Review by jagpreetsinghsasan — CHANGES_REQUESTED** [review]
Have you tested this one?
Because how will `cd supplychain` gonna work?
We do not have the applications anymore in the bevel repository. They are hosted [here](https://github.com/hyperledger/bevel-samples)

**Comment by octonawish-akcodes** [comment]
How can I test it?

**Comment by suvajit-sarkar** [comment]
Adding app molecule test would require adding the molecule test cases, the work flow won't do anything otherwise

**Comment by octonawish-akcodes** [comment]
Are there any sample test cases I can get idea from, also where should the test cases be placed in the bevel-sample repo or in this repo?

**Comment by sownak** [comment]
@octonawish-akcodes molecule tests are in `platforms/shared/configuration/molecule` which can be referred. Tests for sample will be in the other repo

**Pull request closed without merging**
