### PR TITLE
[ci-skip] Pods crashes post Kubernetes cluster nodes are restarted

### PR DESCRIPTION
**Pull request by mgCepeda**
Primary Changes
--------------
1. Fixed permission denied error for vault.
2. Fixed vault-auth bug 
3. Fixed removal of vault policies for r3-corda

Modifications in roles and tpl files
-----------------------
platforms/quorum/configuration/roles/create/k8_component/templates/reviewer_rbac.tpl 
platforms/r3-corda-ent/configuration/roles/create/k8_component/templates/reviewer_rbac.tpl 
platforms/r3-corda/configuration/roles/create/k8_component/templates/reviewer_rbac.tpl 
platforms/r3-corda/configuration/roles/delete/vault_secrets/tasks/nested_main.yaml

### CODE REVIEW

**Comment by adityajoshi12** [comment]
@mgCepeda do we need similar changes for fabric and besu?

**Comment by suvajit-sarkar** [comment]
> @mgCepeda do we need similar changes for fabric and besu? I observed similar issue with besu.

the fixes were done for besu and fabric.

**Comment by adityajoshi12** [comment]
> > @mgCepeda do we need similar changes for fabric and besu? I observed similar issue with besu.
> 
> the fixes were done for besu and fabric.

Thanks for the update, can you point me that PR.

**Comment by mgCepeda** [comment]
> > > @mgCepeda do we need similar changes for fabric and besu? I observed similar issue with besu.
> > 
> > 
> > the fixes were done for besu and fabric.
> 
> Thanks for the update, can you point me that PR.

**Comment by mgCepeda** [comment]
> > > @mgCepeda do we need similar changes for fabric and besu? I observed similar issue with besu.
> > 
> > 
> > the fixes were done for besu and fabric.
> 
> Thanks for the update, can you point me that PR.

The PR is https://github.com/hyperledger/bevel/pull/2152

**Pull request merged**
